### ISSUE TITLE
HTTP error code 408

### ISSUE THREAD

**Issue by espiegel** [mixpanel/mixpanel-java#15]
I'm getting a bunch of these errors every once in a while:

Server returned HTTP response code: 408 for URL: http://api.mixpanel.com/track?ip=0 

After I perform: mixPanelApi.deliver(delivery)

I'm just wondering if anyone else encountered this issue

**Comment by chook** [comment]
#14 also speaks about this.

**Comment by joeatwork** [comment]
I'm going to close this as a duplicate of #14 - @espiegel , I'm going to tag you in that issue so that you can follow progress there.
