### ISSUE TITLE
Java library should use https by default

### ISSUE THREAD

**Issue by robnunn** [mixpanel/mixpanel-java#18]
Given the sensitive nature of the data that is being transmitted to Mixpanel servers, https should be enabled by default. At the moment we have to use `new MixpanelAPI("https://api.mixpanel.com/track", "https://api.mixpanel.com/engage")` which is not ideal. If there is some reason why https can't be used by default, then a new constructor with a boolean useHttps parameter could be added instead.

**Comment by JensRantil** [comment]
:+1:
