### ISSUE TITLE
Java client reference still refers to 1.4.2.

### ISSUE THREAD

**Issue by JensRantil** [mixpanel/mixpanel-java#19]
https://mixpanel.com/help/reference/java still refers to 1.4.2 even though 1.4.3 was pushed to [Maven Central](http://search.maven.org/#artifactdetails%7Ccom.mixpanel%7Cmixpanel-java%7C1.4.3%7Cjar) a [long time ago](https://github.com/mixpanel/mixpanel-java/issues/12#issuecomment-54646880). Any reason for this? Or simply a miss in documentation?

**Comment by patedit** [comment]
Changed to 1.4.4. The change will be live soon. Thanks.
