### ISSUE TITLE
Connect timeout not set

### ISSUE THREAD

**Issue by JensRantil** [mixpanel/mixpanel-java#20]
#12 only fixated a read timeout. However, a sane Java library should also set connect timeout, which defaults to infinity. Without setting it, the client risks locking up an entire application that has fixed number of threads (which most do).

See also 9f945f39423de7408d4ad220cdada0721b383607.

**Comment by avram** [comment]
I had only set the read timeout because that was the one causing issues. Makes sense to me that the connect timeout should also be set to a reasonable value.

**Comment by JensRantil** [comment]
@avram Thanks for getting back on this. I'll make sure to submit a pull request.

**Comment by avram** [comment]
Also, I should note that I'm not the maintainer of this project, so I don't know what Mixpanel feels about the change. Let's hope they agree!

**Comment by JensRantil** [comment]
@avram No no, I got that :) Just wanted to check with you if there was a special reason for not setting it.
