### ISSUE TITLE
Make socket timeouts configurable

### ISSUE THREAD

**Issue by JensRantil** [mixpanel/mixpanel-java#21]
Problem: Currently the socket read timeout applied in 9f945f39423de7408d4ad220cdada0721b383607 is hardcoded. Two minutes is waay long for us since we are making very many small `POST`s.

Request: Make timeout configurable. This should also apply to the connect timeout mentioned in #20.

**Comment by JensRantil** [comment]
Closing this. The timeouts are fairly low now so I don't think is no longer an issue. Let me know if you'd like me to reopen this.

**Comment by AartiKriplani** [comment]
Recently Mixpanel API was down and we had a lot of connection timeouts which made our servers really slow. It would be great if the connection and read timeouts are configurable so we can set them to lower values and especially during such outages
