### ISSUE TITLE
Publish a new Maven artefact

### ISSUE THREAD

**Issue by JensRantil** [mixpanel/mixpanel-java#27]
Now that #23, #24, #25 & #26 has been merged, would it be possible for you to push a new maven artefact to maven central? You might also want to fix #19 while you are at it.

(ping @patedit)

**Comment by JensRantil** [comment]
Oh, currently we are using an internally package maven package with the fixed previously merged. The reason I'd love a new version published is 1) so your end users can benefit from the changes and 2) so we don't need to host our own fork of this library.

**Comment by patedit** [comment]
A new version has been released.

**Comment by JensRantil** [comment]
:+1: Thanks.
