### ISSUE TITLE
Passing $email in storing user profiles gives error

### ISSUE THREAD

**Issue by krupak** [mixpanel/mixpanel-java#28]
Hi, I am required to have mixpanel integrate with my Grails project. When I pass $email property in JSONObject while creating the user profile it gives error. As $email property is required to send email notification from the mixpanel site. 
Kindly help with some example to set $email property for user profiles so that I can send email notification.

Thanks and awaiting your reply.

**Comment by JensRantil** [comment]
@krupak This repository is rather dead. You might get a faster response by contacting the Mixpanel support.

**Comment by patedit** [comment]
Hi @krupak! Following this example: https://github.com/mixpanel/mixpanel-java/blob/master/src/demo/java/com/mixpanel/mixpanelapi/demo/MixpanelAPIDemo.java#L95

You should be able to add
`namePropsMap.put("$email", "krupak@github.com");`

What's the problem that you are having? :)

**Comment by krupak** [comment]
Thanks :+1:
